<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <script>
        // let p = new Promise((resolve, reject) => {
        //     console.log("promises id pending");
        //     setTimeout(() => {
        //         resolve(true);
        //     }, 3000);
        // })
        // p.then((v) => {
        //     console.log(v);
        // })


        // //  console.log(p); // the state is in the pendding sate bec of the settimeout
        // let p1 = new Promise((resolve, reject) => {
        //     console.log("promises id pending");
        //     setTimeout(() => {
        //         reject(new Error("i am an new error"));
        //     }, 3000);
        // })

        // p1.catch((err) => {
        //     console.log(" some mistake is happened in p1 plz check it out bro");
        // })

        // let na= new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         console.log("plz i am tried");  
        //         resolve(true);
        //     }, 3000);
        // })
        
        // na.then((v)=>{
        //   console.log(v);
        // })

        // let manu= new Promise((resolve, reject) => {
        
        // })
        
       
        //then and catch in 1 statement
       //let p= new Promise((resolve, reject) => {
     //        setTimeout(() => {
     //             console.log("hello")
     //             resolve(true);
     //             reject(new Error("i am an error"))
     //        },2000);
     //   })

     //   p.then((v)=>{
     //     console.log(v);
     //   }).catch((err)=>{
     //    console.log(err);
     //   })
       
     //   let p1= new Promise((resolve, reject) => {
     //        setTimeout(() => {
     //             console.log("hello")
     //           reject(new Error("i am an error"))
     //        },2000);
     //   })

       

    //    p1.catch((err)=>{
    //     console.log(err);
    //    })

    


//promise with harry bai
// let p= new Promise((resolve, reject) => {
//      console.log("program1");
//     setTimeout(() => {
//       console.log("1st program is solved");
//      //  resolve(33);
//      reject(new Error("it gone wrong bro"));
//     }, 2000);
// })
// p.then((v)=>{
//      console.log(v);
// }).catch((er)=>{
//      console.log(er);
// })

// let p1= new Promise((resolve, reject) => {
//      console.log("program2 ");
//     setTimeout(() => {
//       console.log("1st program is rejected");
//       reject(new Error("it have an error"));
//     }, 2000);
// })
// p1.catch((er)=>{
//      console.log(er);
// })

    </script>
</body>

</html>